name: Secret and Variable Demo

on:
  workflow_dispatch:

jobs:
  show-bands:
    runs-on: ubuntu-latest
    steps:

      - name: Echo secret
        run: echo "Don't tell anyone, but my favorite band is ${{ secrets.FAV_BAND_SECRET }}."
        
      - name: Echo variable
        run: echo "Don't tell anyone, but my OTHER favorite band is ${{ vars.FAV_BAND_VAR }}."
